import { IstateRate } from "../@types/taxtypes";

export const USAstates: IstateRate[] = [
  { "state": "Alabama", "purchaseRate": 5.25 },
  { "state": "Alaska", "purchaseRate": 5.20 },
  { "state": "Arizona", "purchaseRate": 5.15 },
  { "state": "Arkansas", "purchaseRate": 5.18 },
  { "state": "California", "purchaseRate": 5.10 },
  { "state": "Colorado", "purchaseRate": 5.12 },
  { "state": "Connecticut", "purchaseRate": 5.07 },
  { "state": "Delaware", "purchaseRate": 5.09 },
  { "state": "Florida", "purchaseRate": 5.05 },
  { "state": "Georgia", "purchaseRate": 5.22 },
  { "state": "Hawaii", "purchaseRate": 5.08 },
  { "state": "Idaho", "purchaseRate": 5.25 },
  { "state": "Illinois", "purchaseRate": 5.20 },
  { "state": "Indiana", "purchaseRate": 5.23 },
  { "state": "Iowa", "purchaseRate": 5.27 },
  { "state": "Kansas", "purchaseRate": 5.20 },
  { "state": "Kentucky", "purchaseRate": 5.24 },
  { "state": "Louisiana", "purchaseRate": 5.28 },
  { "state": "Maine", "purchaseRate": 5.30 },
  { "state": "Maryland", "purchaseRate": 5.06 },
  { "state": "Massachusetts", "purchaseRate": 5.05 },
  { "state": "Michigan", "purchaseRate": 5.19 },
  { "state": "Minnesota", "purchaseRate": 5.17 },
  { "state": "Mississippi", "purchaseRate": 5.28 },
  { "state": "Missouri", "purchaseRate": 5.22 },
  { "state": "Montana", "purchaseRate": 5.30 },
  { "state": "Nebraska", "purchaseRate": 5.15 },
  { "state": "Nevada", "purchaseRate": 5.12 },
  { "state": "New Hampshire", "purchaseRate": 5.06 },
  { "state": "New Jersey", "purchaseRate": 5.03 },
  { "state": "New Mexico", "purchaseRate": 5.14 },
  { "state": "New York", "purchaseRate": 5.02 },
  { "state": "North Carolina", "purchaseRate": 5.25 },
  { "state": "North Dakota", "purchaseRate": 5.19 },
  { "state": "Ohio", "purchaseRate": 5.28 },
  { "state": "Oklahoma", "purchaseRate": 5.13 },
  { "state": "Oregon", "purchaseRate": 5.07 },
  { "state": "Pennsylvania", "purchaseRate": 5.04 },
  { "state": "Rhode Island", "purchaseRate": 5.12 },
  { "state": "South Carolina", "purchaseRate": 5.18 },
  { "state": "South Dakota", "purchaseRate": 5.06 },
  { "state": "Tennessee", "purchaseRate": 5.31 },
  { "state": "Texas", "purchaseRate": 5.01 },
  { "state": "Utah", "purchaseRate": 5.30 },
  { "state": "Vermont", "purchaseRate": 5.28 },
  { "state": "Virginia", "purchaseRate": 5.03 },
  { "state": "Washington", "purchaseRate": 5.09 },
  { "state": "West Virginia", "purchaseRate": 5.15 },
  { "state": "Wisconsin", "purchaseRate": 5.22 },
  { "state": "Wyoming", "purchaseRate": 5.32 }
]
